name: Java CI Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
         java-version: '17'
         distribution: 'corretto'

    - name: display java version
      run: java --version

    - name: Build with Maven
      run: mvn --batch-mode -DskipTests  package 

    - name: Run Tests
      run: mvn test

    - name: Run JAR
      run: java -jar target/*.jar 10
